name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: '버전 번호 (예: 1.0.0)'
        required: false

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        include:
          - os: macos-latest
            build-command: npm run build:mac
          - os: windows-latest
            build-command: npm run build:win
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check environment variables
        shell: bash
        run: |
          if [ -z "${{ secrets.MASTER_ADMIN_PASSWORD }}" ]; then
            echo "⚠️ MASTER_ADMIN_PASSWORD가 설정되지 않았습니다. 기본값을 사용합니다."
          else
            echo "✅ MASTER_ADMIN_PASSWORD가 설정되었습니다."
          fi
      
      - name: Build app
        run: ${{ matrix.build-command }}
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false
          MASTER_ADMIN_PASSWORD: ${{ secrets.MASTER_ADMIN_PASSWORD }}
          PUBLISH: never
          GH_TOKEN: ""
          GITHUB_TOKEN: ""
          CI: "true"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/
          retention-days: 30
